### ISSUE TITLE
Deleted schedule isn't removed from DatabaseScheduler.schedule in memory

### ISSUE THREAD

**Issue by minsis** [AngelLiang/celery-sqlalchemy-scheduler#24]
When deleting a schedule from the database it is not removed from memory so when DatabaseScheduler checks for tasks to execute it will error out, but yet will still continue to execute the script.

Adding new schedule:
```
[2020-10-16 12:57:35,634: INFO/MainProcess] DatabaseScheduler: Schedule changed.
[2020-10-16 12:57:35,634: INFO/MainProcess] Writing entries...

Execution of scheulde:
[2020-10-16 13:02:36,313: INFO/MainProcess] Scheduler: Sending due task splunk task (engine.modules.degradation_splunk.tasks.submit_splunk_job)
[2020-10-16 13:02:52,139: INFO/MainProcess] Writing entries...
```

After deletion of entry from database there is no trigger like DatabaseScheduler: Schedule changed.

After deletion it continues to run the task with traceback:
```
[2020-10-16 13:07:36,411: INFO/MainProcess] Scheduler: Sending due task splunk task (engine.modules.degradation_splunk.tasks.submit_splunk_job)
[2020-10-16 13:09:00,097: INFO/MainProcess] Writing entries...
[2020-10-16 13:09:00,551: ERROR/MainProcess] 'NoneType' object has no attribute 'last_run_at'
Traceback (most recent call last):
  File "/home/dwhitney/miniconda3/envs/scorecardv2_engine/lib/python3.8/site-packages/celery_sqlalchemy_scheduler/schedulers.py", line 370, in sync
    self.schedule[name].save()  # save to database
  File "/home/dwhitney/miniconda3/envs/scorecardv2_engine/lib/python3.8/site-packages/celery_sqlalchemy_scheduler/schedulers.py", line 183, in save
    setattr(obj, field, getattr(self.model, field))
AttributeError: 'NoneType' object has no attribute 'last_run_at'
```

**Comment by minsis** [comment]
This is how I delete. Is there supposed to be a different way of doing this?

```python
db.session.query(PeriodicTask).filter(PeriodicTask.id == task_id).delete()
```

**Comment by minsis** [comment]
Ok after some digging around and reading the docs, this is somewhat of a limitation with sqlalchemy. Long story short using the .delete() method on a query doesn't trigger the 'after_delete' event listener. The delete has to be done on the instanced object itself using the session.

```python
db.session.delete(db.session.query(PeriodicTask).get(task_id))
db.session.commit()
```

Maybe there can be some examples or documentation added to this repo to explain that.

**Comment by AngelLiang** [comment]
Thank you very much! I Added note about this in README.md.
