### ISSUE TITLE
新增任务或者修改状态,beat会报错并中止进程

### ISSUE THREAD

**Issue by guyuecode** [AngelLiang/celery-sqlalchemy-scheduler#34]
系统环境: CentOS 7.8 or Windows 10
Python版本:  3.6.8
Celery版本: 4.2.2

结合Flask使用的，新增任务会触发报错并中止beat进程
经过测试发现，新增或修改以seconds之外为间隔单位的Interval类型任务会报错，就算我强制修改数据库，也不会调度任务
使用seconds单位的任务反而没有问题..

报错如下:

PS D:\GIT仓库\flask-demo> .\venv\Scripts\python.exe -m  celery -A celery_worker.celery_app beat -S celery_sqlalchemy_scheduler.schedulers:DatabaseScheduler --loglevel=DEBUG
celery beat v4.2.2 (windowlicker) is starting.
D:\GIT仓库\flask-demo\venv\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 491")
  result = self._query(query)
__    -    ... __   -        _
LocalTime -> 2021-07-12 18:32:41
Configuration ->
    . broker -> redis://127.0.0.1:6379/2
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery_sqlalchemy_scheduler.schedulers.DatabaseScheduler
    . db -> mysql+pymysql://root:123456@localhost/dev-devops
    . logfile -> [stderr]@%DEBUG
    . maxinterval -> 5.00 seconds (5s)
[2021-07-12 18:34:32,678: WARNING/MainProcess] Traceback (most recent call last):
[2021-07-12 18:34:32,678: WARNING/MainProcess] File "C:\Users\xxxx\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 193, in _run_module_as_main
[2021-07-12 18:34:32,680: WARNING/MainProcess] "__main__", mod_spec)
[2021-07-12 18:34:32,683: WARNING/MainProcess] File "C:\Users\xxxx\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 85, in _run_code
[2021-07-12 18:34:32,684: WARNING/MainProcess] exec(code, run_globals)
[2021-07-12 18:34:32,684: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\__main__.py", line 20, in <module>
[2021-07-12 18:34:32,685: WARNING/MainProcess] main()
[2021-07-12 18:34:32,685: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\__main__.py", line 16, in main
[2021-07-12 18:34:32,686: WARNING/MainProcess] _main()
[2021-07-12 18:34:32,686: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\bin\celery.py", line 322, in main
[2021-07-12 18:34:32,688: WARNING/MainProcess] cmd.execute_from_commandline(argv)
[2021-07-12 18:34:32,690: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\bin\celery.py", line 496, in execute_from_commandline
[2021-07-12 18:34:32,698: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
[2021-07-12 18:34:32,698: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\bin\base.py", line 275, in execute_from_commandline
[2021-07-12 18:34:32,699: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
[2021-07-12 18:34:32,699: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\bin\celery.py", line 488, in handle_argv
[2021-07-12 18:34:32,700: WARNING/MainProcess] return self.execute(command, argv)
[2021-07-12 18:34:32,700: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\bin\celery.py", line 420, in execute
[2021-07-12 18:34:32,702: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2021-07-12 18:34:32,702: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\bin\base.py", line 279, in run_from_argv
[2021-07-12 18:34:32,704: WARNING/MainProcess] sys.argv if argv is None else argv, command)
[2021-07-12 18:34:32,711: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\bin\base.py", line 363, in handle_argv
[2021-07-12 18:34:32,713: WARNING/MainProcess] return self(*args, **options)
[2021-07-12 18:34:32,714: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\bin\base.py", line 238, in __call__
[2021-07-12 18:34:32,715: WARNING/MainProcess] ret = self.run(*args, **kwargs)
[2021-07-12 18:34:32,716: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\bin\beat.py", line 109, in run
[2021-07-12 18:34:32,717: WARNING/MainProcess] return beat().run()
[2021-07-12 18:34:32,720: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\apps\beat.py", line 81, in run
[2021-07-12 18:34:32,721: WARNING/MainProcess] self.start_scheduler()
[2021-07-12 18:34:32,725: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\apps\beat.py", line 109, in start_scheduler
[2021-07-12 18:34:32,726: WARNING/MainProcess] service.start()
[2021-07-12 18:34:32,727: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\beat.py", line 588, in start
[2021-07-12 18:34:32,727: WARNING/MainProcess] interval = self.scheduler.tick()
[2021-07-12 18:34:32,727: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\beat.py", line 293, in tick
[2021-07-12 18:34:32,728: WARNING/MainProcess] self.populate_heap()
[2021-07-12 18:34:32,729: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery\beat.py", line 267, in populate_heap
[2021-07-12 18:34:32,729: WARNING/MainProcess] is_due, next_call_delay = entry.is_due()
[2021-07-12 18:34:32,731: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\celery_sqlalchemy_scheduler\schedulers.py", line 126, in is_due
[2021-07-12 18:34:32,731: WARNING/MainProcess] if not self.model.enabled:
[2021-07-12 18:34:32,731: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 287, in __get__
[2021-07-12 18:34:32,732: WARNING/MainProcess] return self.impl.get(instance_state(instance), dict_)
[2021-07-12 18:34:32,733: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 718, in get
[2021-07-12 18:34:32,734: WARNING/MainProcess] value = state._load_expired(state, passive)
[2021-07-12 18:34:32,736: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\sqlalchemy\orm\state.py", line 652, in _load_expired
[2021-07-12 18:34:32,737: WARNING/MainProcess] self.manager.deferred_scalar_loader(self, toload)
[2021-07-12 18:34:32,740: WARNING/MainProcess] File "D:\GIT仓库\flask-demo\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 946, in load_scalar_attributes
[2021-07-12 18:34:32,741: WARNING/MainProcess] "attribute refresh operation cannot proceed" % (state_str(state))
[2021-07-12 18:34:32,742: WARNING/MainProcess] sqlalchemy.orm.exc
[2021-07-12 18:34:32,743: WARNING/MainProcess] .
[2021-07-12 18:34:32,743: WARNING/MainProcess] DetachedInstanceError
[2021-07-12 18:34:32,744: WARNING/MainProcess] :
[2021-07-12 18:34:32,744: WARNING/MainProcess] Instance <PeriodicTask at 0x23ba47c8ac8> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)

**Comment by guyuecode** [comment]
我把数据库中kwargs的值从单引号改为双引号后就好了..
估计是jsonload出错了
{ 'var1': 'value1'} ==> {"var1": "value1"}
